version: "2"
services:

  webserver:
    build: ./webserver
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"